### ISSUE TITLE
Shorter output

### ISSUE THREAD

**Issue by osteenbergen** [spriteCloud/teelogger#4]
Teelogger is too verbose for normal debugging:

```
irb(main):003:0> error("Hello World!")
E, [2015-06-02T15:20:30.582614 #18900] ERROR -- #<IO:0x00000001879578>: Hello World!
```

Suggested output:

```
[2015-06-02T15:20:30] Error: Hello World!
```

**Comment by ghost** [comment]
There's a few things we can change, yes, but probably not (all of) those.
1. The first `E` is the log level, and it's set by Ruby's logger - we shouldn't change that (even if we can).
2. A timestamp with sub-second accuracy is very useful for busy logs. Again, we probably shouldn't change that.
3. I'm not sure of the `ERROR` string's source; we're not adding it.
4. The `#<IO:...>` stuff - or, to be more precise, what's in between `--` and `:` is the log name, added by the Ruby logger. We're putting the class or file name there by default. This is largely superfluous and could go, it just helps when logging e.g. to both STDOUT and STDERR.

So, yeah, we could change a bit... but most of it comes from Ruby's logger.

**Comment by ghost** [comment]
Solution is as follows:

``` ruby
irb> log = TeeLogger::TeeLogger.new
irb> log.error("Hello, world!")
=> "E, [2015-07-03T14:21:44+0200 #10589] STDOUT: Hello, world!"
```

That's a more concise default, omitting nanosecond timestamps for the sake of time zone information, and omitting the duplication of the log level.

For debugging, you can use this:

``` ruby
irb> log = TeeLogger::TeeLogger.new
irb> log.formatter = TeeLogger::Formatter.new(TeeLogger::Formatter::FORMAT_SHORT)
irb> log.error("Hello, world!")
=> "E, [2015-07-03T14:21:44+0200] Hello, world!"
```

**Comment by ghost** [comment]
Need to fix the timestamp-related test cases, then it's good to go.

**Comment by ghost** [comment]
a155839 fixes the test cases.
